image: node:16
before_script:
  - apt-get update -qq
  - apt-get install -qq git dos2unix
  - apt-get install -y sudo
  - mkdir ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - echo $SSH_PRIVATE_KEY >> ~/.ssh/key_64.pem
  - cat ~/.ssh/key_64.pem |base64 -d > ~/.ssh/key.pem
  - chmod 400 ~/.ssh/key.pem
  - eval "$(ssh-agent -s)"
#####SSH PRO
  - echo $SSH_PRIVATE_KEY_PRO >> ~/.ssh/key_64_PRO.pem
  - cat ~/.ssh/key_64_PRO.pem |base64 -d > ~/.ssh/key_PRO.pem
  - chmod 400 ~/.ssh/key_PRO.pem
  - eval "$(ssh-agent -s)"
stages:
  - build
  - deploy

build:
  stage: build
  only:
    - qa
  script:
  - node -v
  - yarn install
  - REACT_APP_APIURL=10.198.73.15:4040
  - REACT_APP_PSWD=$REACT_APP_PSWD
  - yarn build 
  stage: build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  only:
    - qa
  script:
    - sudo scp  -i ~/.ssh/key.pem  -r build/* $USUARIO@$IP_REMOTEQA:$DOCUMENT_ROOT

  stage: deploy
  dependencies:
    - build
    
build_pro:
  stage: build
  only:
    - main
  script:
  - node -v
  - yarn install
  - REACT_APP_APIURL=10.198.71.36:4040
  - yarn build
  stage: build
  artifacts:
    paths:
      - build/

deploy_pro:
  stage: deploy
  only:
    - main
  script:
    - sudo scp  -i ~/.ssh/key_PRO.pem  -r build/* $USUARIO@$IP_REMOTE_PRO:$DOCUMENT_ROOT

  stage: deploy
  dependencies:
    - build    
